# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

["Finding Dory", "Rogue One: A Star Wars Story", "Captain America: Civil War", "The Secret Life of Pets", "The Jungle Book", "Deadpool", "Zootopia", "Batman v Superman: Dawn of Justice", "Suicide Squad", "Doctor Strange", "Fantastic Beasts and Where to Find Them", "Moana", "Star Wars Ep. VII: The Force Awakens", "The Revenant", "Sing", "Jason Bourne", "Star Trek Beyond", "X-Men: Apocalypse", "Trolls", "Kung Fu Panda 3", "Ghostbusters", "Central Intelligence", "The Legend of Tarzan", "Sully", "Bad Moms", "The Angry Birds Movie", "Independence Day: Resurgence", "The Conjuring 2: The Enfield Poltergeist", "Sausage Party", "The Magnificent Seven", "Arrival", "Ride Along 2", "Don’t Breathe", "Miss Peregrine’s Home for Peculiar Children", "The Accountant", "Teenage Mutant Ninja Turtles: Out of the Shadows", "The Purge: Election Year", "Alice Through the Looking Glass", "Pete’s Dragon", "The Girl on the Train", "Tyler Perry’s Boo! A Madea Halloween", "Storks", "10 Cloverfield Lane", "Lights Out", "The Divergent Series: Allegiant", "Now You See Me 2", "Hacksaw Ridge", "Ice Age: Collision Course", "The Boss", "London Has Fallen", "Miracles from Heaven", "Deepwater Horizon", "Passengers", "My Big Fat Greek Wedding 2", "Jack Reacher: Never Go Back", "Daddy’s Home", "Me Before You", "The BFG", "Neighbors 2: Sorority Rising", "The Shallows", "Barbershop: The Next Cut", "13 Hours: The Secret Soldiers of Benghazi", "Office Christmas Party", "Kubo and the Two Strings", "The Huntsman: Winter’s War", "Warcraft", "How to be Single", "Mike and Dave Need Wedding Dates", "War Dogs", "Almost Christmas", "Money Monster", "Assassin’s Creed", "Allied", "Nerve", "The Big Short", "Risen", "The Nice Guys", "The Boy", "Dirty Grandpa", "Ouija: Origin of Evil", "The 5th Wave", "Why Him?", "La La Land", "Inferno", "Mother’s Day", "Gods of Egypt", "Hail, Caesar!", "When the Bough Breaks", "Fences", "Zoolander 2", "Hello, My Name is Doris", "Manchester-by-the Sea", "The Finest Hours", "Florence Foster Jenkins", "Hell or High Water", "The Forest", "Ben-Hur", "Collateral Beauty", "Sisters", "The Witch"].each do |name|
  Movie.where(name: name).first_or_create
end
